// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Calculator Library")]
[assembly: AssemblyDescriptionAttribute("Sample Project for the dotnetpro FAKE Article")]
[assembly: GuidAttribute("8617DA9B-055D-4B27-8D74-D36BA9C821E2")]
[assembly: AssemblyProductAttribute("Calculator")]
[assembly: AssemblyVersionAttribute("0.2")]
[assembly: AssemblyFileVersionAttribute("0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2";
    }
}
