// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Calculator Command Line Application")]
[assembly: AssemblyDescriptionAttribute("Sample Project for the dotnetpro FAKE Article")]
[assembly: GuidAttribute("96CAFDED-19CC-4409-AD99-454311AC76C8")]
[assembly: AssemblyProductAttribute("Calculator")]
[assembly: AssemblyVersionAttribute("0.1")]
[assembly: AssemblyFileVersionAttribute("0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1";
    }
}
