// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Calculator Library Tests")]
[assembly: AssemblyDescriptionAttribute("Sample Project for the dotnetpro FAKE Article")]
[assembly: GuidAttribute("DC26E96E-23D5-45D0-B19C-FFDD0432402F")]
[assembly: AssemblyProductAttribute("Calculator")]
[assembly: AssemblyVersionAttribute("15.12")]
[assembly: AssemblyFileVersionAttribute("15.12")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "15.12";
    }
}
